/** \file
 *  This C header file was generated by $ANTLR version 3.2 Sep 23, 2009 12:02:23
 *
 *     -  From the grammar source file : pycf.g
 *     -                            On : 2014-05-20 19:56:56
 *     -                for the parser : pycfParserParser *
 * Editing it, at least manually, is not wise. 
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
 * The parser pycfParser has the callable functions (rules) shown below,
 * which will invoke the code for the associated rule in the source grammar
 * assuming that the input stream is pointing to a token/text stream that could begin
 * this rule.
 * 
 * For instance if you call the first (topmost) rule in a parser grammar, you will
 * get the results of a full parse, but calling a rule half way through the grammar will
 * allow you to pass part of a full token stream to the parser, such as for syntax checking
 * in editors and so on.
 *
 * The parser entry points are called indirectly (by function pointer to function) via
 * a parser context typedef ppycfParser, which is returned from a call to pycfParserNew().
 *
 * The methods in ppycfParser are  as follows:
 *
 *  - pycfParser_file_input_return      ppycfParser->file_input(ppycfParser)
 *  - pycfParser_decorator_return      ppycfParser->decorator(ppycfParser)
 *  - pycfParser_decorators_return      ppycfParser->decorators(ppycfParser)
 *  - pycfParser_decor_arglist_return      ppycfParser->decor_arglist(ppycfParser)
 *  - pycfParser_funcdef_return      ppycfParser->funcdef(ppycfParser)
 *  - pycfParser_parameters_return      ppycfParser->parameters(ppycfParser)
 *  - pycfParser_defparameter_return      ppycfParser->defparameter(ppycfParser)
 *  - pycfParser_varargslist_return      ppycfParser->varargslist(ppycfParser)
 *  - pycfParser_fpdef_return      ppycfParser->fpdef(ppycfParser)
 *  - pycfParser_fplist_return      ppycfParser->fplist(ppycfParser)
 *  - pycfParser_stmt_return      ppycfParser->stmt(ppycfParser)
 *  - pycfParser_simple_stmt_return      ppycfParser->simple_stmt(ppycfParser)
 *  - pycfParser_small_stmt_return      ppycfParser->small_stmt(ppycfParser)
 *  - pycfParser_expr_stmt_return      ppycfParser->expr_stmt(ppycfParser)
 *  - pycfParser_augassign_return      ppycfParser->augassign(ppycfParser)
 *  - pycfParser_print_stmt_return      ppycfParser->print_stmt(ppycfParser)
 *  - pycfParser_printlist_return      ppycfParser->printlist(ppycfParser)
 *  - pycfParser_del_stmt_return      ppycfParser->del_stmt(ppycfParser)
 *  - pycfParser_pass_stmt_return      ppycfParser->pass_stmt(ppycfParser)
 *  - pycfParser_flow_stmt_return      ppycfParser->flow_stmt(ppycfParser)
 *  - pycfParser_break_stmt_return      ppycfParser->break_stmt(ppycfParser)
 *  - pycfParser_continue_stmt_return      ppycfParser->continue_stmt(ppycfParser)
 *  - pycfParser_return_stmt_return      ppycfParser->return_stmt(ppycfParser)
 *  - pycfParser_yield_stmt_return      ppycfParser->yield_stmt(ppycfParser)
 *  - pycfParser_raise_stmt_return      ppycfParser->raise_stmt(ppycfParser)
 *  - pycfParser_import_stmt_return      ppycfParser->import_stmt(ppycfParser)
 *  - pycfParser_import_name_return      ppycfParser->import_name(ppycfParser)
 *  - pycfParser_import_from_return      ppycfParser->import_from(ppycfParser)
 *  - pycfParser_import_path_return      ppycfParser->import_path(ppycfParser)
 *  - pycfParser_import_as_name_return      ppycfParser->import_as_name(ppycfParser)
 *  - pycfParser_dotted_as_name_return      ppycfParser->dotted_as_name(ppycfParser)
 *  - pycfParser_import_as_names_return      ppycfParser->import_as_names(ppycfParser)
 *  - pycfParser_dotted_as_names_return      ppycfParser->dotted_as_names(ppycfParser)
 *  - pycfParser_dotted_name_return      ppycfParser->dotted_name(ppycfParser)
 *  - pycfParser_global_stmt_return      ppycfParser->global_stmt(ppycfParser)
 *  - pycfParser_exec_stmt_return      ppycfParser->exec_stmt(ppycfParser)
 *  - pycfParser_assert_stmt_return      ppycfParser->assert_stmt(ppycfParser)
 *  - pycfParser_nonlocal_stmt_return      ppycfParser->nonlocal_stmt(ppycfParser)
 *  - pycfParser_compound_stmt_return      ppycfParser->compound_stmt(ppycfParser)
 *  - pycfParser_if_stmt_return      ppycfParser->if_stmt(ppycfParser)
 *  - pycfParser_elif_clause_return      ppycfParser->elif_clause(ppycfParser)
 *  - pycfParser_while_stmt_return      ppycfParser->while_stmt(ppycfParser)
 *  - pycfParser_for_stmt_return      ppycfParser->for_stmt(ppycfParser)
 *  - pycfParser_try_stmt_return      ppycfParser->try_stmt(ppycfParser)
 *  - pycfParser_try_closure_return      ppycfParser->try_closure(ppycfParser)
 *  - pycfParser_except_closure_return      ppycfParser->except_closure(ppycfParser)
 *  - pycfParser_with_stmt_return      ppycfParser->with_stmt(ppycfParser)
 *  - pycfParser_with_item_return      ppycfParser->with_item(ppycfParser)
 *  - pycfParser_except_clause_return      ppycfParser->except_clause(ppycfParser)
 *  - pycfParser_suite_return      ppycfParser->suite(ppycfParser)
 *  - pycfParser_testlist_safe_return      ppycfParser->testlist_safe(ppycfParser)
 *  - pycfParser_old_test_return      ppycfParser->old_test(ppycfParser)
 *  - pycfParser_old_lambdef_return      ppycfParser->old_lambdef(ppycfParser)
 *  - pycfParser_test_return      ppycfParser->test(ppycfParser)
 *  - pycfParser_or_test_return      ppycfParser->or_test(ppycfParser)
 *  - pycfParser_and_test_return      ppycfParser->and_test(ppycfParser)
 *  - pycfParser_not_test_return      ppycfParser->not_test(ppycfParser)
 *  - pycfParser_comparison_return      ppycfParser->comparison(ppycfParser)
 *  - pycfParser_comp_op_return      ppycfParser->comp_op(ppycfParser)
 *  - pycfParser_expr_return      ppycfParser->expr(ppycfParser)
 *  - pycfParser_xor_expr_return      ppycfParser->xor_expr(ppycfParser)
 *  - pycfParser_and_expr_return      ppycfParser->and_expr(ppycfParser)
 *  - pycfParser_shift_expr_return      ppycfParser->shift_expr(ppycfParser)
 *  - pycfParser_arith_expr_return      ppycfParser->arith_expr(ppycfParser)
 *  - pycfParser_term_return      ppycfParser->term(ppycfParser)
 *  - pycfParser_factor_return      ppycfParser->factor(ppycfParser)
 *  - pycfParser_power_return      ppycfParser->power(ppycfParser)
 *  - pycfParser_atom_return      ppycfParser->atom(ppycfParser)
 *  - pycfParser_listmaker_return      ppycfParser->listmaker(ppycfParser)
 *  - pycfParser_testlist_comp_return      ppycfParser->testlist_comp(ppycfParser)
 *  - pycfParser_lambdef_return      ppycfParser->lambdef(ppycfParser)
 *  - pycfParser_trailer_return      ppycfParser->trailer(ppycfParser)
 *  - pycfParser_subscriptlist_return      ppycfParser->subscriptlist(ppycfParser)
 *  - pycfParser_subscript_return      ppycfParser->subscript(ppycfParser)
 *  - pycfParser_sliceop_return      ppycfParser->sliceop(ppycfParser)
 *  - pycfParser_exprlist_return      ppycfParser->exprlist(ppycfParser)
 *  - pycfParser_testlist_return      ppycfParser->testlist(ppycfParser)
 *  - pycfParser_dictorsetmaker_return      ppycfParser->dictorsetmaker(ppycfParser)
 *  - pycfParser_dictmakerclause_return      ppycfParser->dictmakerclause(ppycfParser)
 *  - pycfParser_setmakerclause_return      ppycfParser->setmakerclause(ppycfParser)
 *  - pycfParser_classdef_return      ppycfParser->classdef(ppycfParser)
 *  - pycfParser_inheritancelist_return      ppycfParser->inheritancelist(ppycfParser)
 *  - pycfParser_arglist_return      ppycfParser->arglist(ppycfParser)
 *  - pycfParser_argument_return      ppycfParser->argument(ppycfParser)
 *  - pycfParser_list_iter_return      ppycfParser->list_iter(ppycfParser)
 *  - pycfParser_list_for_return      ppycfParser->list_for(ppycfParser)
 *  - pycfParser_list_if_return      ppycfParser->list_if(ppycfParser)
 *  - pycfParser_comp_iter_return      ppycfParser->comp_iter(ppycfParser)
 *  - pycfParser_comp_for_return      ppycfParser->comp_for(ppycfParser)
 *  - pycfParser_comp_if_return      ppycfParser->comp_if(ppycfParser)
 *  - pycfParser_testlist1_return      ppycfParser->testlist1(ppycfParser)
 *  - pycfParser_yield_expr_return      ppycfParser->yield_expr(ppycfParser)
 *  - pycfParser_string_return      ppycfParser->string(ppycfParser)
 *
 * The return type for any particular rule is of course determined by the source
 * grammar file.
 */
// [The "BSD licence"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

#ifndef	_pycfParser_H
#define _pycfParser_H
/* =============================================================================
 * Standard antlr3 C runtime definitions
 */
#include    <antlr3.h>

/* End of standard antlr 3 runtime definitions
 * =============================================================================
 */
 
#ifdef __cplusplus
extern "C" {
#endif

// Forward declare the context typedef so that we can use it before it is
// properly defined. Delegators and delegates (from import statements) are
// interdependent and their context structures contain pointers to each other
// C only allows such things to be declared if you pre-declare the typedef.
//
typedef struct pycfParser_Ctx_struct pycfParser, * ppycfParser;



#ifdef	ANTLR3_WINDOWS
// Disable: Unreferenced parameter,							- Rules with parameters that are not used
//          constant conditional,							- ANTLR realizes that a prediction is always true (synpred usually)
//          initialized but unused variable					- tree rewrite variables declared but not needed
//          Unreferenced local variable						- lexer rule declares but does not always use _type
//          potentially unitialized variable used			- retval always returned from a rule 
//			unreferenced local function has been removed	- susually getTokenNames or freeScope, they can go without warnigns
//
// These are only really displayed at warning level /W4 but that is the code ideal I am aiming at
// and the codegen must generate some of these warnings by necessity, apart from 4100, which is
// usually generated when a parser rule is given a parameter that it does not use. Mostly though
// this is a matter of orthogonality hence I disable that one.
//
#pragma warning( disable : 4100 )
#pragma warning( disable : 4101 )
#pragma warning( disable : 4127 )
#pragma warning( disable : 4189 )
#pragma warning( disable : 4505 )
#pragma warning( disable : 4701 )
#endif

/* ========================
 * BACKTRACKING IS ENABLED
 * ========================
 */
typedef struct pycfParser_file_input_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    pycfParser_file_input_return;

typedef struct pycfParser_decorator_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    pycfParser_decorator_return;

typedef struct pycfParser_decorators_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    pycfParser_decorators_return;

typedef struct pycfParser_decor_arglist_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    pycfParser_decor_arglist_return;

typedef struct pycfParser_funcdef_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    pycfParser_funcdef_return;

typedef struct pycfParser_parameters_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    pycfParser_parameters_return;

typedef struct pycfParser_defparameter_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    pycfParser_defparameter_return;

typedef struct pycfParser_varargslist_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    pycfParser_varargslist_return;

typedef struct pycfParser_fpdef_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    pycfParser_fpdef_return;

typedef struct pycfParser_fplist_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    pycfParser_fplist_return;

typedef struct pycfParser_stmt_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    pycfParser_stmt_return;

typedef struct pycfParser_simple_stmt_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    pycfParser_simple_stmt_return;

typedef struct pycfParser_small_stmt_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    pycfParser_small_stmt_return;

typedef struct pycfParser_expr_stmt_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    pycfParser_expr_stmt_return;

typedef struct pycfParser_augassign_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    pycfParser_augassign_return;

typedef struct pycfParser_print_stmt_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    pycfParser_print_stmt_return;

typedef struct pycfParser_printlist_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    pycfParser_printlist_return;

typedef struct pycfParser_del_stmt_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    pycfParser_del_stmt_return;

typedef struct pycfParser_pass_stmt_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    pycfParser_pass_stmt_return;

typedef struct pycfParser_flow_stmt_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    pycfParser_flow_stmt_return;

typedef struct pycfParser_break_stmt_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    pycfParser_break_stmt_return;

typedef struct pycfParser_continue_stmt_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    pycfParser_continue_stmt_return;

typedef struct pycfParser_return_stmt_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    pycfParser_return_stmt_return;

typedef struct pycfParser_yield_stmt_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    pycfParser_yield_stmt_return;

typedef struct pycfParser_raise_stmt_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    pycfParser_raise_stmt_return;

typedef struct pycfParser_import_stmt_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    pycfParser_import_stmt_return;

typedef struct pycfParser_import_name_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    pycfParser_import_name_return;

typedef struct pycfParser_import_from_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    pycfParser_import_from_return;

typedef struct pycfParser_import_path_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    pycfParser_import_path_return;

typedef struct pycfParser_import_as_name_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    pycfParser_import_as_name_return;

typedef struct pycfParser_dotted_as_name_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    pycfParser_dotted_as_name_return;

typedef struct pycfParser_import_as_names_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    pycfParser_import_as_names_return;

typedef struct pycfParser_dotted_as_names_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    pycfParser_dotted_as_names_return;

typedef struct pycfParser_dotted_name_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    pycfParser_dotted_name_return;

typedef struct pycfParser_global_stmt_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    pycfParser_global_stmt_return;

typedef struct pycfParser_exec_stmt_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    pycfParser_exec_stmt_return;

typedef struct pycfParser_assert_stmt_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    pycfParser_assert_stmt_return;

typedef struct pycfParser_nonlocal_stmt_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    pycfParser_nonlocal_stmt_return;

typedef struct pycfParser_compound_stmt_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    pycfParser_compound_stmt_return;

typedef struct pycfParser_if_stmt_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    pycfParser_if_stmt_return;

typedef struct pycfParser_elif_clause_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    pycfParser_elif_clause_return;

typedef struct pycfParser_while_stmt_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    pycfParser_while_stmt_return;

typedef struct pycfParser_for_stmt_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    pycfParser_for_stmt_return;

typedef struct pycfParser_try_stmt_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    pycfParser_try_stmt_return;

typedef struct pycfParser_try_closure_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    pycfParser_try_closure_return;

typedef struct pycfParser_except_closure_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    pycfParser_except_closure_return;

typedef struct pycfParser_with_stmt_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    pycfParser_with_stmt_return;

typedef struct pycfParser_with_item_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    pycfParser_with_item_return;

typedef struct pycfParser_except_clause_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    pycfParser_except_clause_return;

typedef struct pycfParser_suite_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    pycfParser_suite_return;

typedef struct pycfParser_testlist_safe_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    pycfParser_testlist_safe_return;

typedef struct pycfParser_old_test_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    pycfParser_old_test_return;

typedef struct pycfParser_old_lambdef_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    pycfParser_old_lambdef_return;

typedef struct pycfParser_test_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    pycfParser_test_return;

typedef struct pycfParser_or_test_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    pycfParser_or_test_return;

typedef struct pycfParser_and_test_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    pycfParser_and_test_return;

typedef struct pycfParser_not_test_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    pycfParser_not_test_return;

typedef struct pycfParser_comparison_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    pycfParser_comparison_return;

typedef struct pycfParser_comp_op_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    pycfParser_comp_op_return;

typedef struct pycfParser_expr_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    pycfParser_expr_return;

typedef struct pycfParser_xor_expr_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    pycfParser_xor_expr_return;

typedef struct pycfParser_and_expr_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    pycfParser_and_expr_return;

typedef struct pycfParser_shift_expr_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    pycfParser_shift_expr_return;

typedef struct pycfParser_arith_expr_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    pycfParser_arith_expr_return;

typedef struct pycfParser_term_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    pycfParser_term_return;

typedef struct pycfParser_factor_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    pycfParser_factor_return;

typedef struct pycfParser_power_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    pycfParser_power_return;

typedef struct pycfParser_atom_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    pycfParser_atom_return;

typedef struct pycfParser_listmaker_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    pycfParser_listmaker_return;

typedef struct pycfParser_testlist_comp_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    pycfParser_testlist_comp_return;

typedef struct pycfParser_lambdef_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    pycfParser_lambdef_return;

typedef struct pycfParser_trailer_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    pycfParser_trailer_return;

typedef struct pycfParser_subscriptlist_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    pycfParser_subscriptlist_return;

typedef struct pycfParser_subscript_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    pycfParser_subscript_return;

typedef struct pycfParser_sliceop_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    pycfParser_sliceop_return;

typedef struct pycfParser_exprlist_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    pycfParser_exprlist_return;

typedef struct pycfParser_testlist_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    pycfParser_testlist_return;

typedef struct pycfParser_dictorsetmaker_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    pycfParser_dictorsetmaker_return;

typedef struct pycfParser_dictmakerclause_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    pycfParser_dictmakerclause_return;

typedef struct pycfParser_setmakerclause_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    pycfParser_setmakerclause_return;

typedef struct pycfParser_classdef_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    pycfParser_classdef_return;

typedef struct pycfParser_inheritancelist_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    pycfParser_inheritancelist_return;

typedef struct pycfParser_arglist_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    pycfParser_arglist_return;

typedef struct pycfParser_argument_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    pycfParser_argument_return;

typedef struct pycfParser_list_iter_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    pycfParser_list_iter_return;

typedef struct pycfParser_list_for_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    pycfParser_list_for_return;

typedef struct pycfParser_list_if_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    pycfParser_list_if_return;

typedef struct pycfParser_comp_iter_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    pycfParser_comp_iter_return;

typedef struct pycfParser_comp_for_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    pycfParser_comp_for_return;

typedef struct pycfParser_comp_if_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    pycfParser_comp_if_return;

typedef struct pycfParser_testlist1_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    pycfParser_testlist1_return;

typedef struct pycfParser_yield_expr_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    pycfParser_yield_expr_return;

typedef struct pycfParser_string_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    pycfParser_string_return;



/** Context tracking structure for pycfParser
 */
struct pycfParser_Ctx_struct
{
    /** Built in ANTLR3 context tracker contains all the generic elements
     *  required for context tracking.
     */
    pANTLR3_PARSER   pParser;


     pycfParser_file_input_return (*file_input)	(struct pycfParser_Ctx_struct * ctx);
     pycfParser_decorator_return (*decorator)	(struct pycfParser_Ctx_struct * ctx);
     pycfParser_decorators_return (*decorators)	(struct pycfParser_Ctx_struct * ctx);
     pycfParser_decor_arglist_return (*decor_arglist)	(struct pycfParser_Ctx_struct * ctx);
     pycfParser_funcdef_return (*funcdef)	(struct pycfParser_Ctx_struct * ctx);
     pycfParser_parameters_return (*parameters)	(struct pycfParser_Ctx_struct * ctx);
     pycfParser_defparameter_return (*defparameter)	(struct pycfParser_Ctx_struct * ctx);
     pycfParser_varargslist_return (*varargslist)	(struct pycfParser_Ctx_struct * ctx);
     pycfParser_fpdef_return (*fpdef)	(struct pycfParser_Ctx_struct * ctx);
     pycfParser_fplist_return (*fplist)	(struct pycfParser_Ctx_struct * ctx);
     pycfParser_stmt_return (*stmt)	(struct pycfParser_Ctx_struct * ctx);
     pycfParser_simple_stmt_return (*simple_stmt)	(struct pycfParser_Ctx_struct * ctx);
     pycfParser_small_stmt_return (*small_stmt)	(struct pycfParser_Ctx_struct * ctx);
     pycfParser_expr_stmt_return (*expr_stmt)	(struct pycfParser_Ctx_struct * ctx);
     pycfParser_augassign_return (*augassign)	(struct pycfParser_Ctx_struct * ctx);
     pycfParser_print_stmt_return (*print_stmt)	(struct pycfParser_Ctx_struct * ctx);
     pycfParser_printlist_return (*printlist)	(struct pycfParser_Ctx_struct * ctx);
     pycfParser_del_stmt_return (*del_stmt)	(struct pycfParser_Ctx_struct * ctx);
     pycfParser_pass_stmt_return (*pass_stmt)	(struct pycfParser_Ctx_struct * ctx);
     pycfParser_flow_stmt_return (*flow_stmt)	(struct pycfParser_Ctx_struct * ctx);
     pycfParser_break_stmt_return (*break_stmt)	(struct pycfParser_Ctx_struct * ctx);
     pycfParser_continue_stmt_return (*continue_stmt)	(struct pycfParser_Ctx_struct * ctx);
     pycfParser_return_stmt_return (*return_stmt)	(struct pycfParser_Ctx_struct * ctx);
     pycfParser_yield_stmt_return (*yield_stmt)	(struct pycfParser_Ctx_struct * ctx);
     pycfParser_raise_stmt_return (*raise_stmt)	(struct pycfParser_Ctx_struct * ctx);
     pycfParser_import_stmt_return (*import_stmt)	(struct pycfParser_Ctx_struct * ctx);
     pycfParser_import_name_return (*import_name)	(struct pycfParser_Ctx_struct * ctx);
     pycfParser_import_from_return (*import_from)	(struct pycfParser_Ctx_struct * ctx);
     pycfParser_import_path_return (*import_path)	(struct pycfParser_Ctx_struct * ctx);
     pycfParser_import_as_name_return (*import_as_name)	(struct pycfParser_Ctx_struct * ctx);
     pycfParser_dotted_as_name_return (*dotted_as_name)	(struct pycfParser_Ctx_struct * ctx);
     pycfParser_import_as_names_return (*import_as_names)	(struct pycfParser_Ctx_struct * ctx);
     pycfParser_dotted_as_names_return (*dotted_as_names)	(struct pycfParser_Ctx_struct * ctx);
     pycfParser_dotted_name_return (*dotted_name)	(struct pycfParser_Ctx_struct * ctx);
     pycfParser_global_stmt_return (*global_stmt)	(struct pycfParser_Ctx_struct * ctx);
     pycfParser_exec_stmt_return (*exec_stmt)	(struct pycfParser_Ctx_struct * ctx);
     pycfParser_assert_stmt_return (*assert_stmt)	(struct pycfParser_Ctx_struct * ctx);
     pycfParser_nonlocal_stmt_return (*nonlocal_stmt)	(struct pycfParser_Ctx_struct * ctx);
     pycfParser_compound_stmt_return (*compound_stmt)	(struct pycfParser_Ctx_struct * ctx);
     pycfParser_if_stmt_return (*if_stmt)	(struct pycfParser_Ctx_struct * ctx);
     pycfParser_elif_clause_return (*elif_clause)	(struct pycfParser_Ctx_struct * ctx);
     pycfParser_while_stmt_return (*while_stmt)	(struct pycfParser_Ctx_struct * ctx);
     pycfParser_for_stmt_return (*for_stmt)	(struct pycfParser_Ctx_struct * ctx);
     pycfParser_try_stmt_return (*try_stmt)	(struct pycfParser_Ctx_struct * ctx);
     pycfParser_try_closure_return (*try_closure)	(struct pycfParser_Ctx_struct * ctx);
     pycfParser_except_closure_return (*except_closure)	(struct pycfParser_Ctx_struct * ctx);
     pycfParser_with_stmt_return (*with_stmt)	(struct pycfParser_Ctx_struct * ctx);
     pycfParser_with_item_return (*with_item)	(struct pycfParser_Ctx_struct * ctx);
     pycfParser_except_clause_return (*except_clause)	(struct pycfParser_Ctx_struct * ctx);
     pycfParser_suite_return (*suite)	(struct pycfParser_Ctx_struct * ctx);
     pycfParser_testlist_safe_return (*testlist_safe)	(struct pycfParser_Ctx_struct * ctx);
     pycfParser_old_test_return (*old_test)	(struct pycfParser_Ctx_struct * ctx);
     pycfParser_old_lambdef_return (*old_lambdef)	(struct pycfParser_Ctx_struct * ctx);
     pycfParser_test_return (*test)	(struct pycfParser_Ctx_struct * ctx);
     pycfParser_or_test_return (*or_test)	(struct pycfParser_Ctx_struct * ctx);
     pycfParser_and_test_return (*and_test)	(struct pycfParser_Ctx_struct * ctx);
     pycfParser_not_test_return (*not_test)	(struct pycfParser_Ctx_struct * ctx);
     pycfParser_comparison_return (*comparison)	(struct pycfParser_Ctx_struct * ctx);
     pycfParser_comp_op_return (*comp_op)	(struct pycfParser_Ctx_struct * ctx);
     pycfParser_expr_return (*expr)	(struct pycfParser_Ctx_struct * ctx);
     pycfParser_xor_expr_return (*xor_expr)	(struct pycfParser_Ctx_struct * ctx);
     pycfParser_and_expr_return (*and_expr)	(struct pycfParser_Ctx_struct * ctx);
     pycfParser_shift_expr_return (*shift_expr)	(struct pycfParser_Ctx_struct * ctx);
     pycfParser_arith_expr_return (*arith_expr)	(struct pycfParser_Ctx_struct * ctx);
     pycfParser_term_return (*term)	(struct pycfParser_Ctx_struct * ctx);
     pycfParser_factor_return (*factor)	(struct pycfParser_Ctx_struct * ctx);
     pycfParser_power_return (*power)	(struct pycfParser_Ctx_struct * ctx);
     pycfParser_atom_return (*atom)	(struct pycfParser_Ctx_struct * ctx);
     pycfParser_listmaker_return (*listmaker)	(struct pycfParser_Ctx_struct * ctx);
     pycfParser_testlist_comp_return (*testlist_comp)	(struct pycfParser_Ctx_struct * ctx);
     pycfParser_lambdef_return (*lambdef)	(struct pycfParser_Ctx_struct * ctx);
     pycfParser_trailer_return (*trailer)	(struct pycfParser_Ctx_struct * ctx);
     pycfParser_subscriptlist_return (*subscriptlist)	(struct pycfParser_Ctx_struct * ctx);
     pycfParser_subscript_return (*subscript)	(struct pycfParser_Ctx_struct * ctx);
     pycfParser_sliceop_return (*sliceop)	(struct pycfParser_Ctx_struct * ctx);
     pycfParser_exprlist_return (*exprlist)	(struct pycfParser_Ctx_struct * ctx);
     pycfParser_testlist_return (*testlist)	(struct pycfParser_Ctx_struct * ctx);
     pycfParser_dictorsetmaker_return (*dictorsetmaker)	(struct pycfParser_Ctx_struct * ctx);
     pycfParser_dictmakerclause_return (*dictmakerclause)	(struct pycfParser_Ctx_struct * ctx);
     pycfParser_setmakerclause_return (*setmakerclause)	(struct pycfParser_Ctx_struct * ctx);
     pycfParser_classdef_return (*classdef)	(struct pycfParser_Ctx_struct * ctx);
     pycfParser_inheritancelist_return (*inheritancelist)	(struct pycfParser_Ctx_struct * ctx);
     pycfParser_arglist_return (*arglist)	(struct pycfParser_Ctx_struct * ctx);
     pycfParser_argument_return (*argument)	(struct pycfParser_Ctx_struct * ctx);
     pycfParser_list_iter_return (*list_iter)	(struct pycfParser_Ctx_struct * ctx);
     pycfParser_list_for_return (*list_for)	(struct pycfParser_Ctx_struct * ctx);
     pycfParser_list_if_return (*list_if)	(struct pycfParser_Ctx_struct * ctx);
     pycfParser_comp_iter_return (*comp_iter)	(struct pycfParser_Ctx_struct * ctx);
     pycfParser_comp_for_return (*comp_for)	(struct pycfParser_Ctx_struct * ctx);
     pycfParser_comp_if_return (*comp_if)	(struct pycfParser_Ctx_struct * ctx);
     pycfParser_testlist1_return (*testlist1)	(struct pycfParser_Ctx_struct * ctx);
     pycfParser_yield_expr_return (*yield_expr)	(struct pycfParser_Ctx_struct * ctx);
     pycfParser_string_return (*string)	(struct pycfParser_Ctx_struct * ctx);
     ANTLR3_BOOLEAN (*synpred5_pycf)	(struct pycfParser_Ctx_struct * ctx);
     ANTLR3_BOOLEAN (*synpred8_pycf)	(struct pycfParser_Ctx_struct * ctx);
     ANTLR3_BOOLEAN (*synpred20_pycf)	(struct pycfParser_Ctx_struct * ctx);
     ANTLR3_BOOLEAN (*synpred56_pycf)	(struct pycfParser_Ctx_struct * ctx);
     ANTLR3_BOOLEAN (*synpred57_pycf)	(struct pycfParser_Ctx_struct * ctx);
     ANTLR3_BOOLEAN (*synpred90_pycf)	(struct pycfParser_Ctx_struct * ctx);
     ANTLR3_BOOLEAN (*synpred144_pycf)	(struct pycfParser_Ctx_struct * ctx);
     ANTLR3_BOOLEAN (*synpred147_pycf)	(struct pycfParser_Ctx_struct * ctx);
     ANTLR3_BOOLEAN (*synpred165_pycf)	(struct pycfParser_Ctx_struct * ctx);
     ANTLR3_BOOLEAN (*synpred180_pycf)	(struct pycfParser_Ctx_struct * ctx);
     ANTLR3_BOOLEAN (*synpred194_pycf)	(struct pycfParser_Ctx_struct * ctx);
    // Delegated rules
    const char * (*getGrammarFileName)();
    void	    (*free)   (struct pycfParser_Ctx_struct * ctx);
    /* @headerFile.members() */
    pANTLR3_BASE_TREE_ADAPTOR	adaptor;
    pANTLR3_VECTOR_FACTORY		vectors;
    /* End @headerFile.members() */
};

// Function protoypes for the constructor functions that external translation units
// such as delegators and delegates may wish to call.
//
ANTLR3_API ppycfParser pycfParserNew         (pANTLR3_COMMON_TOKEN_STREAM instream);
ANTLR3_API ppycfParser pycfParserNewSSD      (pANTLR3_COMMON_TOKEN_STREAM instream, pANTLR3_RECOGNIZER_SHARED_STATE state);

/** Symbolic definitions of all the tokens that the parser will work with.
 * \{
 *
 * Antlr will define EOF, but we can't use that as it it is too common in
 * in C header files and that would be confusing. There is no way to filter this out at the moment
 * so we just undef it here for now. That isn't the value we get back from C recognizers
 * anyway. We are looking for ANTLR3_TOKEN_EOF.
 */
#ifdef	EOF
#undef	EOF
#endif
#ifdef	Tokens
#undef	Tokens
#endif 
#define EXCEPT_STMT      37
#define EXPONENT      92
#define STAR      52
#define NONZERODIGIT      82
#define T__159      159
#define T__158      158
#define WHAT      23
#define TRIAPOS      73
#define NONZEROOCTDIGIT      87
#define T__160      160
#define LONGBYTES      77
#define EOF      -1
#define IMPORT_STMT      22
#define BREAK_STMT      11
#define T__161      161
#define LEADING_WS      97
#define DBL_STAR_ARG      34
#define OCTINTEGER      79
#define RPAREN      50
#define NAME      54
#define NAME_ARG      32
#define STRING_LITERAL      40
#define DICTIONARY      39
#define FINALLY_STMT      36
#define T__148      148
#define T__147      147
#define T__149      149
#define DOTTED_NAME      18
#define CONTINUE_STMT      12
#define BODY      8
#define COMMENT      48
#define T__154      154
#define SHORTBYTES      76
#define T__155      155
#define T__156      156
#define T__99      99
#define T__157      157
#define T__98      98
#define T__150      150
#define T__151      151
#define T__152      152
#define T__153      153
#define RBRACK      60
#define T__139      139
#define T__138      138
#define T__137      137
#define T__136      136
#define ARGUMENTS      46
#define ESCAPESEQ      72
#define LCURLY      61
#define FUNC_DEF      7
#define T__141      141
#define LIST      38
#define T__142      142
#define T__140      140
#define T__145      145
#define GLOBAL_STMT      21
#define T__146      146
#define T__143      143
#define T__144      144
#define T__126      126
#define SHORTSTRING      70
#define T__125      125
#define T__128      128
#define DECOR      17
#define T__127      127
#define WS      96
#define T__129      129
#define WHILE_STMT      28
#define INTPART      90
#define BINDIGIT      86
#define NOT_IN      41
#define BYTESLITERAL      68
#define FLOATNUMBER      65
#define LONGINT      64
#define PASS_STMT      10
#define T__130      130
#define T__131      131
#define T__132      132
#define T__133      133
#define T__134      134
#define T__135      135
#define EXPONENTFLOAT      89
#define CONTINUED_LINE      95
#define LBRACK      59
#define CLASS_INHERITANCE      45
#define DOUBLESTAR      53
#define ELSE_STMT      26
#define T__118      118
#define BYTESPREFIX      75
#define T__119      119
#define T__116      116
#define T__117      117
#define TRY_STMT      35
#define T__114      114
#define TEST_LIST      31
#define T__115      115
#define OCTDIGIT      84
#define T__124      124
#define BININTEGER      81
#define T__123      123
#define T__122      122
#define T__121      121
#define T__120      120
#define DEDENT      5
#define ELIF_STMT      27
#define DEL_STMT      9
#define POINTFLOAT      88
#define LPAREN      49
#define WITH_STMT      30
#define INDENT      4
#define PRINT_STMT      16
#define STRINGPREFIX      69
#define AS      24
#define IS_NOT      42
#define T__107      107
#define COMMA      51
#define T__108      108
#define T__109      109
#define T__103      103
#define T__104      104
#define EXEC_STMT      20
#define IF_STMT      25
#define T__105      105
#define T__106      106
#define T__111      111
#define T__110      110
#define T__113      113
#define T__112      112
#define DIGIT      83
#define DOT      58
#define IMAGNUMBER      66
#define RETURN_STMT      13
#define INTEGER      63
#define T__102      102
#define HEXINTEGER      80
#define T__101      101
#define T__100      100
#define STAR_ARG      33
#define SEMI      56
#define LONGSTRING      71
#define YIELD_STMT      15
#define TRIQUOTE      74
#define COLON      55
#define HEAD_NAME      44
#define TRAILER_NAME      43
#define FOR_STMT      29
#define ASSERT_STMT      19
#define NEWLINE      47
#define STRINGLITERAL      67
#define RCURLY      62
#define ID_CONTINUE      94
#define ASSIGN      57
#define DECIMALINTEGER      78
#define RAISE_STMT      14
#define FRACTION      91
#define ID_START      93
#define CLASS_DEF      6
#define HEXDIGIT      85
#ifdef	EOF
#undef	EOF
#define	EOF	ANTLR3_TOKEN_EOF
#endif

#ifndef TOKENSOURCE
#define TOKENSOURCE(lxr) lxr->pLexer->rec->state->tokSource
#endif

/* End of token definitions for pycfParser
 * =============================================================================
 */
/** \} */

#ifdef __cplusplus
}
#endif

#endif

/* END - Note:Keep extra line feed to satisfy UNIX systems */
